import { CartProvider } from "@/context/CartContext";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Script from "next/script"; // ✅ import Script

export const metadata = {
  title: "Vehicle Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
       {/* <Script
  src="https://www.paypal.com/sdk/js?client-id=AdJq94sV-y0iXYIkLUiIHVxfvD7BhvAf-XGMaRS_olKSrj4lON1jIANscPFI2FKPhJx3HPqog1Q84-re&components=buttons&disable-funding=paylater,venmo"
  strategy="beforeInteractive"
/> */}
<Script
  src="https://www.paypal.com/sdk/js?client-id=AdJq94sV-y0iXYIkLUiIHVxfvD7BhvAf-XGMaRS_olKSrj4lON1jIANscPFI2FKPhJx3HPqog1Q84-re"
  strategy="beforeInteractive"
/>
      </head>
      <body className="bg-white text-black">
        <CartProvider>
          <Header />
          <main className="min-h-[90vh] px-4">{children}</main>
          <Footer />
          <ToastContainer />
        </CartProvider>
      </body>
    </html>
  );
}
